### ISSUE TITLE
URL to be whitelisted for Microclimate to work

### ISSUE THREAD

**Issue by arjunsbabu** [microclimate-dev2ops/microclimate-dev2ops.github.io#76]
**Issue type:** Question
**Reported in:** 1.10 installed on ICp 3.1.0
**Description of issue:* Like to know the URL to be white listed for Microclimate and jenkins  to work*

HI Team,
We are running microclimate behind a firewall and currently all outbound connectivity is allowed.
Our project us based on nodejs. We are planning to restrict internet access and allow access to only  certain urls which are required for microclimate and for docker build. I have refered the link https://microclimate.dev/offlinemicroclimateusing#doc 
Hence we noted some urls to be whitelisted.

**Microclimate portal**
https://code.jquery.com
https://cdnjs.cloudflare.com
https://unpkg.com

**Jenkins Library**
https://github.com

**Other Url**
docker.io
quay.io

Please help us to append the list of urls to be whitelisted that are required for microclimate and jenkins in the list above.
Our docker build use some other repositories and we will note it down separately.

**Comment by rajivnathan** [comment]
Please note that only the Microclimate pipeline supports offline scenarios. See https://microclimate.dev/offlinemicroclimateusing#doc

Using the rest of Microclimate in an air-gapped environment is not officially supported at this time. However, some have had success whitelisting the following (depends on the project type):

General: 
 docker.io

Maven Central for Microprofile/Spring:
 repo1.maven.org
 repo.maven.apache.org

NPM for NodeJS:
 registry.npmjs.org

Swift:
 githubusercontent.com
 github.com

Microprofile:
 asset-websphere.ibm.com
 public.dhe.ibm.com
 github.com
 APT update/install: archive.ubuntu.com / security.ubuntu.com


Furthermore, if whitelisting is not an option you may be able to modify the project files to work in an air-gapped environment.

For Microprofile projects for example:

1. You can create a settings.xml file that defines a local nexus (or other) repository that has dependencies that your project needs and ensure it is copied into the m2 home directory in the image by modifying the Dockerfile.
See https://maven.apache.org/settings.html#Repositories and https://maven.apache.org/settings.html#Plugin_Repositories
2. Host any required Liberty features locally. Use the Liberty "installUtility" command to download any Liberty features required for your project and package them into a zip that can then be copied into the image using the Dockerfile or create an on-premises repository. Then you would have to create a repositories.properties file in the Liberty install directory (I think it would be /opt/ibm/wlp/etc ) to disable the use of the default repository.
3. Modify the Dockerfile to retrieve any assets from internally accessible servers rather than downloading them from external URIs.

**Comment by arjunsbabu** [comment]
Thanks for the reply @rajivnathan for sharing the urls and recommendation to build the project . We dont need microclimate offline as it need multiple settings to be done. We are ok to whitelist any URL. But the challenge is to collect all required URLs. There is a separate team working to whitelist urls required for  nodejs project.
Let me summarize the URLs required for microclimate. Please let me know whether I am missing any

**Microclimate portal**
https://code.jquery.com
https://cdnjs.cloudflare.com
https://unpkg.com


**Jenkins Library**
https://github.com
repo1.maven.org
repo.maven.apache.org
registry.npmjs.org
githubusercontent.com
github.com
asset-websphere.ibm.com
public.dhe.ibm.com
github.com
asset-websphere.ibm.com
public.dhe.ibm.com
github.com
maven.apache.org


**Other Url**
docker.io
quay.io

Please let us know any additional url is required for microclimate and jenkins. 
As i said we are not concerned about the dependencies required during docker build but  still i have included registry.npmjs.org because it may be required for jenkins to build nodejs.

**Comment by rajivnathan** [comment]
I'm not aware of any missing URLs from that list. However, you are missing some URLs from the list I provided. eg. archive.ubuntu.com

**Comment by arjunsbabu** [comment]
Thanks @rajivnathan  for your help
